[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "shared-functions"
version = "0.1.0"
description = "Library containing shared functions used in DMIS."
dependencies = [
    "requests>=2.32",
]

[tool.setuptools]
package-dir = {"" = "shared_functions"}
