[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "refresh-service"
version = "0.0.1"
description = "Logging API"
dynamic = ["dependencies"]

[tool.setuptools]
package-dir = {"" = "src"}

[project.scripts]
refresh-service = "refresh_service.api:run"
refresh-worker = "refresh_service.token_refresh:run"
