name: dmis_app

services:
  log-api:
    container_name: log-api
    hostname: log-api
    build:
      context: .
      dockerfile: src/logger/api/Dockerfile
    restart: always
    environment:
      LOGAPI_BIND_ADDR: ""
      LOGAPI_BIND_PORT: ""
      LOGAPI_LOGDB_DATABASE: ""
      LOGAPI_LOGDB_PASSW: ""
      LOGAPI_LOGDB_URL: ""
      LOGAPI_LOGDB_USER: ""

  log-database:
    container_name: log-database
    hostname: log-database
    build:
      context: .
      dockerfile: src/logger/database/Dockerfile
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ""
      MYSQL_PASSWORD: ""
      MYSQL_RANDOM_ROOT_PASSWORD: ""
      MYSQL_USER: ""

  search-engine:
    container_name: search-engine
    hostname: search-engine
    build:
      context: .
      dockerfile: src/search_engine/Dockerfile
    restart: always
    volumes:
      - search-engine-cache:/data
    environment:
      SEARCHENG_BIND_ADDR: ""
      SEARCHENG_BIND_PORT: ""
      SEARCHENG_CLASSIFIER_URL: ""
      SEARCHENG_CONGATEWAY_URL: ""
      SEARCHENG_STOCHAN_URL: ""
      SEARCHENG_WORKING_DIRECTORY: ""
      LOGAPI_URL: ""

  connector-gateway:
    container_name: connector-gateway
    hostname: connector-gateway
    build:
      context: .
      dockerfile: src/connectors/connector-gateway/Dockerfile
    restart: always
    volumes:
      - ./source_systems.json:/etc/source_systems.json
    environment:
      CONGATEWAY_FASTAPI_BIND_ADDR: ""
      CONGATEWAY_FASTAPI_BIND_PORT: ""
      CONGATEWAY_FASTAPI_LOG_LEVEL: ""
      CONGATEWAY_CONFIG_FILE_PATH: ""
      CONGATEWAY_REQUEST_TIMEOUT: ""
      CONGATEWAY_REFRESH_SERVICE_URL: ""
      LOGAPI_URL: ""

  dmis-api:
    container_name: dmis-api
    hostname: dmis-api
    build:
      context: .
      dockerfile: src/api/Dockerfile
    restart: always
    environment:
      DMISAPI_BIND_ADDR: ""
      DMISAPI_BIND_PORT: ""
      DMISAPI_SEARCHENG_URL: ""
      DMISAPI_STOCHAN_URL: ""
      DMISAPI_CONGATEWAY_URL: ""
      DMISAPI_LOGAPI_URL: ""
      DMISAPI_AD_WELL_KNOWN_URL: ""
      DMISAPI_USER_ROLES: ""
      DMISAPI_ADMIN_ROLES: ""
      DMISAPI_AD_URL: ""
      DMISAPI_AD_JWKS_URL: ""
      DMISAPI_AD_ALLOWED_AZP: ""
      DMISAPI_AD_TOKEN_URL: ""
      DMISAPI_AD_LOGOUT_URL: ""
      DMISAPI_AD_CLIENT_ID: ""
      DMISAPI_ACCESS_COOKIE_MAX_AGE: ""
      DMISAPI_REFRESH_COOKIE_MAX_AGE: ""

  front-end:
    container_name: front-end
    hostname: front-end
    build:
      context: ./src/front_end
    restart: always
    environment:
      FRONTEND_AD_CLIENT_ID: ""
      FRONTEND_AD_REALM: ""
      FRONTEND_AD_URL: ""
      FRONTEND_DMISAPI_BASE_URL: ""
      FRONTEND_DMISAPI_URL: ""

  connector-gitlab:
    container_name: connector-gitlab
    hostname: connector-gitlab
    build:
      context: .
      dockerfile: src/connectors/gitlab/Dockerfile
    restart: always
    environment:
      CONGITLAB_BIND_ADDR: ""
      CONGITLAB_BIND_PORT: ""
      CONGITLAB_GITLAB_CLIENT_ID: ""
      CONGITLAB_GITLAB_CLIENT_SECRET: ""
      CONGITLAB_GITLAB_URL: ""
      CONGITLAB_STATE_SIGNING_SECRET: ""
      CONGITLAB_SYSTEM_NAME: ""
      CONGITLAB_CONNECT_SERVICE_CALLBACK: ""
      LOGAPI_URL: ""

  connector-confluence:
    container_name: connector-confluence
    hostname: connector-confluence
    build:
      context: .
      dockerfile: src/connectors/confluence/Dockerfile
    restart: always
    environment:
      CONCONFLUENCE_BIND_PORT: ""
      CONCONFLUENCE_BIND_ADDR: ""
      CONCONFLUENCE_SYSTEM_NAME: ""
      CONCONFLUENCE_CLIENT_ID: ""
      CONCONFLUENCE_CLIENT_SECRET: ""
      CONCONFLUENCE_STATE_SIGNING_SECRET: ""
      CONCONFLUENCE_SCOPES: ""
      CONCONFLUENCE_CONFLUENCE_URL: ""
      CONCONFLUENCE_CLOUD_ID: ""
      CONCONFLUENCE_AUTH_URL: ""
      CONCONFLUENCE_TOKEN_URL: ""
      CONCONFLUENCE_CONNECT_SERVICE_CALLBACK: ""
      CONCONFLUENDE_CHECK_AUTH_URL: ""
      LOGAPI_URL: ""

  connector-samba:
    container_name: connector-samba
    hostname: connector-samba
    build:
      context: .
      dockerfile: src/connectors/samba/Dockerfile
    restart: always
    privileged: true
    environment:
      CONSMB_BIND_ADDR: ""
      CONSMB_BIND_PORT: ""
      CONSMB_SMB_SHARE_ADDR: ""
      CONSMB_SMB_SHARE_PORT: ""
      CONSMB_SMB_SHARE_SERVICE_USER: ""
      CONSMB_SMB_SHARE_SERVICE_PASS: ""
      CONSMB_SMB_SERVICE_MOUNT_PATH: ""
      CONSMB_SMB_USER_MOUNT_PATH: ""
      CONSMB_SYSTEM_NAME: ""
      CONSMB_SMB_SHARE_NAME: ""
      LOGAPI_URL: ""

  connector-lorem:
    container_name: connector-lorem
    hostname: connector-lorem
    build:
      context: .
      dockerfile: src/connectors/lorem/Dockerfile
    restart: always
    environment:
      CONLOREM_BIND_ADDR: ""
      CONLOREM_BIND_PORT: ""
      CONLOREM_STREAM_CAP: ""
      CONLOREM_POINTER_BASE: ""

  connector-github:
    container_name: connector-github
    hostname: connector-github
    build:
      context: .
      dockerfile: src/connectors/github/Dockerfile
    restart: always
    environment:
      CONGITHUB_BIND_ADDR: ""
      CONGITHUB_BIND_PORT: ""
      CONGITHUB_GITHUB_tps: ""
      CONGITHUB_GITHUB_BASE_URL: ""
      CONGITHUB_GITHUB_SYSTEM_NAME: ""
      CONGITHUB_GITHUB_API_VERSION: ""
      CONGITHUB_CLIENT_ID: ""
      CONGITHUB_CLIENT_SECRET: ""
      CONGITHUB_STATE_SIGNING_SECRET: ""
      CONGITHUB_GITHUB_API_URL: ""
      CONGITHUB_CONNECT_SERVICE_CALLBACK: ""
      LOGAPI_URL: ""

  connector-sharepoint:
    container_name: connector-sharepoint
    hostname: connector-sharepoint
    build:
      context: .
      dockerfile: src/connectors/sharepoint/Dockerfile
    restart: always

  refresh_service-redis:
    container_name: refresh_service-redis
    hostname: refresh_service-redis
    build:
      context: .
      dockerfile: src/refresh_service/redis/Dockerfile
    restart: always
    environment:
      REDIS_PORT: ""
      REDIS_PASSWORD: ""
      LOGAPI_URL: ""

  refresh_service-service:
    container_name: refresh-service
    hostname: refresh_service-service
    build:
      context: .
      dockerfile: src/refresh_service/api/Dockerfile
    command: /usr/local/bin/refresh-service
    restart: always
    environment:
      REFSERVICE_BIND_ADDR: ""
      REFSERVICE_BIND_PORT: ""
      REFSERVICE_SESSION_ENC_PASSW: ""
      REFSERVICE_REDIS_HOST: ""
      REFSERVICE_REDIS_PORT: ""
      REFSERVICE_AD_JWKS_URL: ""
      REFSERVICE_AD_URL: ""
      LOGAPI_URL: ""

  refresh_service-worker:
    container_name: refresh-worker
    hostname: refresh_service-worker
    build:
      context: .
      dockerfile: src/refresh_service/api/Dockerfile
    command: /usr/local/bin/refresh-worker
    restart: always
    environment:
      REFSERVICE_BIND_ADDR: ""
      REFSERVICE_BIND_PORT: ""
      REFSERVICE_SESSION_ENC_PASSW: ""
      REFSERVICE_REDIS_HOST: ""
      REFSERVICE_REDIS_PORT: ""
      REFSERVICE_AD_JWKS_URL: ""
      REFSERVICE_AD_URL: ""
      LOGAPI_URL: ""

  stochastic-analyzer:
    container_name: stochastic-analyzer
    hostname: stochastic-analyzer
    build:
      context: .
      dockerfile: src/stochastic_analyzer/Dockerfile
    restart: always

volumes:
  search-engine-cache:
  mysql_data:
  refresh-service.dev.dms-lookup.com: