[tox]
skipsdist = false
requires = 
    tox>=4
envlist = pylint, ruffEnv, formatting_env, mypy-api, unittest_env, frontend_env

[testenv]
deps =
    setuptools
    ruff>=0.6
    pylint>=3
    black
    mypy>=1.19
    types-requests
    types-aiofiles
    ./src/shared_functions
package = wheel

[testenv:pylint]
commands = pylint {toxinidir}/src

[testenv:ruffEnv]
commands = ruff check {toxinidir}/src

[testenv:mypy-api]
setenv =
    MYPYPATH = {toxinidir}/src/shared_functions/logger
commands = mypy src 

[testenv:formatting_env]
commands = black --check {toxinidir}/src

[testenv:unittest_env]
allowlist_externals = pytest
deps = 
    ./src/connectors/gitlab
    ./src/connectors/github
    ./src/search_engine
    ./src/stochastic_analyzer
    pytest>=9.0
    httpx
commands =
    python -m pytest {toxinidir}/src/connectors/gitlab/test
    python -m pytest {toxinidir}/src/connectors/github/test
    python -m pytest {toxinidir}/src/search_engine/test
    python -m pytest {toxinidir}/src/stochastic_analyzer/test
[testenv:frontend_env]
allowlist_externals = npm
change_dir = {toxinidir}/src/front_end
commands = 
    npm install 
    npm run lint
