[tox]
skipsdist = false
requires = 
    tox>=4
envlist = pylint, ruffEnv, formatting_env, mypy-shared_functions, unittest_env

[testenv]
deps =
    ruff>=0.6
    pylint>=3
    black
    mypy>=1.19
    types-requests
package = wheel

[testenv:pylint]
commands = pylint --ignore=.env,venv,__pycache__,.tox,build,.venv --disable=import-error --max-line-length=132 src

[testenv:ruffEnv]
commands = ruff check --exclude .env,venv,__pycache__,.tox,build,.venv {toxinidir}/src

[testenv:mypy-shared_functions]
changedir = src/shared_functions
package = wheel
commands = mypy --disallow-untyped-defs --exclude "(\.env|venv|__pycache__)|\.tox|build" src

[testenv:formatting_env]
commands = black -l 132 --check --exclude "/(\.env|venv|__pycache__)/|\.tox|build" {toxinidir}/src

[testenv:unittest_env]
#TODO, add unittests