[tox]
skipsdist = false
requires = 
    tox>=4
envlist = pylint, ruffEnv, formatting_env, mypy-api, unittest_env

[testenv]
deps =
    setuptools
    ruff>=0.6
    pylint>=3
    black
    mypy>=1.19
    types-requests
package = wheel

[testenv:pylint]
commands = pylint {toxinidir}/src

[testenv:ruffEnv]
commands = ruff check {toxinidir}/src

[testenv:mypy-api]
commands = mypy src

[testenv:formatting_env]
commands = black {toxinidir}/src

[testenv:unittest_env]
#TODO, add unittests