services:
  log-api:
    image: log-api:latest
    environment:
      LOGAPI_BIND_ADDR: "0.0.0.0"
      LOGAPI_BIND_PORT: 8000
      LOGAPI_LOGDB_URL: "log-database"
      LOGAPI_LOGDB_USER: "logger"
      LOGAPI_LOGDB_PASSW: "changeme"
      LOGAPI_LOGDB_DATABASE: "logger"


    build: ./api/
    # command: "--dev" # To enable devloper mode
    ports:
      - "8000:8000"

  log-database:
    image: log-database:latest
    build: ./database
    environment:
      MYSQL_DATABASE: "logger"
      MYSQL_USER: "logger"
      MYSQL_PASSWORD: "changeme"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    # ports:
    #   - "3306:3306"
