services:
  log-api:
    image: log-api:latest
    env_file: ./env/log_api.env
    build: ./api/
    ports:
      - "8000:8000"

  log-database:
    image: log-database:latest
    env_file: ./env/log_database.env
    build: ./database
    ports:
      - "3306:3306"
