[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "confluence_service"
description = "Conflucence connector"
version = "0.1.0"
dynamic = ["dependencies"]

[tool.setuptools]
package-dir = {"" = "src"}

[project.scripts]
confluence_connector = "confluence_service.collector_api:run"
