"""Copyright (c) 2026, Studentprojekt Knowit Cybersecurity and Law"""

TIMEOUT: int = 120

CLASSIFICATION: str = "security_class"
IS_DOCUMENT: str = "is_document"
MODIFIED: str = "modified"
UNIQUE_POINTER: str = "unique_pointer"
CONTENT: str = "content"

BOOLEAN_CATEGORIES: set[str] = {IS_DOCUMENT, MODIFIED}
RAW_CATEGORIES: set[str] = {UNIQUE_POINTER, CLASSIFICATION}
COOKED_CATEGORIES: set[str] = {CONTENT}

CONVERTABLE_TYPES: list[str] = ["255044462d", "504b0304"]  # PDF signature  # ZIP DOCX PPTX ODT XLSX ...

CLASSIFICATION_QUEUE_SIZE: int = 1024
GENERIC_QUEUE_SIZE: int = 1000
POINTER_QUEUE_SIZE: int = 100_000_000

GENERIC_WORKER_COUNT: int = 8

MAX_PENDING_CONTENT_SIZE: int = 50 * 1024 * 1024  # 50MB
MAX_SEARCH_QUERY_LENGTH: int = 512
MAX_FAIL_COUNT: int = 5

INITIAL_RETRY_DELAY: float = 1.0
MAX_RETRY_DELAY: float = 30.0
MAX_RETRY_ATTEMPTS: int = 5
