[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "dmis_api"
version = "0.0.1"
description = "Library for main DMIS main API."
dynamic = ["dependencies"]

[tool.setuptools]
package-dir = {"" = "src"}

[project.scripts]
dmis_api = "dmis_api.api:run"

[tool.ruff.lint]
ignore = ["PLR0913"]