[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dmis_api"
description = "Library for main DMIS main API."
dependencies = [
    "fastapi[standard]>=0.128",
]
dynamic = ["version"]

[tool.setuptools]
package-dir = {"" = "src"}

[project.scripts]
dmis_api = "dmis_api.api:run"
