services:
  log-api:
    image: search-engine:latest
    environment:
      SEARCHENG_BIND_PORT: 8000
      SEARCHENG_CONGATEWAY_URL: "http://10.3.0.2:8000"
    build: ./
    # command: "--dev" # To enable devloper mode
    ports:
      - "8000:8000"
