[build-system]
requires = [
  "setuptools >= 77.0.3",
  "mysql-connector-python >= 9.5",
  "fastapi[standard] >= 0.128",
]
build-backend = "setuptools.build_meta"

[project]
name = "logging_endpoint"
version = "0.0.1"
description = "Logging endpoint"
dependencies = [
  "mysql-connector-python >= 9.5",
  "fastapi[standard] >= 0.128",
]
