services:
  log-api:
    image: log-api:latest
    build: ./logger/api/

  log-database:
    image: log-database:latest
    build: ./logger/database

  search_engine:
    image: search-engine:latest
    build: ./search_engine
