name: Push and Deploy Images

on:
  push:
    branches: ["develop"]

env:
  DEPLOY_DIR: "/opt/dev/"
  COMPOSE_FILE: "docker-compose-build-all.yaml"
  REGISTRY: "registry.dms-lookup.com"

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push images to registry
        run: |
          IMAGES="$(docker compose -f $COMPOSE_FILE config --images)"
          echo "Images from compose:"
          echo "$IMAGES"
          
          # Give every image a tag
          # <image>:latest
          #
          while IFS= read -r img; do
            [ -z "$img" ] && continue
            base="$img"
            if echo "$img" | grep -qE ':[^/]+$'; then
              base="${img%:*}"
            fi
        
            # Strip registry if already present
            base_no_registry="${base#*/}"
        
            full="$REGISTRY/$base_no_registry"
        
            echo "Tagging $img -> $full:latest"
            docker tag "$img" "$full:latest"
            echo "Pushing $full:latest"
            docker push "$full:latest"
          done <<< "$IMAGES"

      - name: Redeploy images
        run: |
          cd $DEPLOY_DIR
          docker compose pull
          docker compose up -d --remove-orphans
